# Generated by Django 2.2.9 on 2020-01-19 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Матиенко Андрей Павлович', max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('morning', models.BooleanField()),
                ('bed', models.BooleanField()),
                ('arrange', models.BooleanField()),
                ('dishware', models.BooleanField()),
                ('aim', models.CharField(max_length=200)),
                ('done', models.BooleanField()),
                ('action', models.TextField()),
                ('good_things', models.TextField()),
                ('bad_things', models.TextField()),
                ('new_thing', models.TextField()),
                ('work_time', models.BooleanField()),
                ('meditation', models.BooleanField()),
                ('thanks', models.TextField()),
                ('charity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('strength', models.TextField()),
                ('tomorrow', models.TextField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
