# Generated by Django 2.2.9 on 2020-01-19 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 14, 16, 14, 688973, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='diary',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
