# Generated by Django 2.2.4 on 2020-01-28 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200128_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 17, 36, 13, 872277, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(blank=True, default='Просто хороший день', max_length=200),
        ),
    ]
