# Generated by Django 2.2.4 on 2020-01-28 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200128_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 17, 43, 3, 36268, tzinfo=utc)),
        ),
    ]
