# Generated by Django 2.2.4 on 2020-01-28 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200128_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='test',
        ),
        migrations.AddField(
            model_name='diary',
            name='PE',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='diary',
            name='arrange',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='diary',
            name='bed',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='diary',
            name='dishware',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='diary',
            name='done',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='diary',
            name='meditation',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='diary',
            name='morning',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='diary',
            name='work_time',
            field=models.CharField(choices=[('1', 'Да'), ('2', 'Нет')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='diary',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 17, 47, 39, 388269, tzinfo=utc)),
        ),
    ]
